server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: rainBow
    password: 312ybj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yuanbaojian.xyz:3306/rain_bow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: 312ybj
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liuhu.rainbow.system.entity
  global-config:
    banner: false


rainbow:
  shiro:
    anonUrl: /login
